### PR TITLE
update comment

### PR DESCRIPTION
**Pull request by chillchillchou**

### CODE REVIEW

**Review by koji — COMMENTED** [review]
line 33 need to use  `.jpeg` instead of `jpg` or `png`?

**Comment by chillchillchou** [comment]
I don’t need to but I don’t know the reason to choose one over another?

**Comment by koji** [comment]
https://github.com/chillchillchou/Face_Matching/blob/master/master_cv_webcam.py#L154
might be `input_name`

fileName --> file_name

**Comment by koji** [comment]
https://github.com/chillchillchou/Face_Matching/blob/master/master_picam.py#L94
what is `photo`?

**Comment by koji** [comment]
https://github.com/chillchillchou/Face_Matching/pull/1/files#diff-1342480b254a5f072ae6dfa0129743d2L132

Can you use `emotion.Confidence`?

**Review by koji — COMMENTED** [review]
Seems emotion type is `number` so you may need to create a function to convert values to a word like sad, happy etc. Maybe aws api has a function for that, but not sure

https://github.com/chillchillchou/Face_Matching/pull/1/files#diff-1342480b254a5f072ae6dfa0129743d2R134

**Comment by koji** [comment]
Closed this since the review function didn't work lol

**Pull request closed without merging**
